spring.application.name=demo

server.port=8081
spring.datasource.url=
spring.datasource.driverClassName=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true


